{% set name = "napari-roi-registration" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-roi-registration-{{ version }}.tar.gz
  sha256: cc7ccdcb7c2dc95b875cfe3c015390c11b9964382b74575f6538b50fd6b95540

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - opencv
    - openpyxl
    - python >=3.8
    - qtpy
    - scikit-image

test:
  imports:
    - napari_roi_registration
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/GiorgiaTortora/napari-roi-registration
  summary: A plugin to perform roi registration.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - GiorgiaTortora
    - goanpeca
    - jaimergp
